### ISSUE TITLE
Many identifiers are undefined behaviour

### ISSUE THREAD

**Issue by manwiththedrip** [cristeigabriel/memscan#1]
The C standard prohibits the decleration of a name starting with "mem" followed by a lowercase letter.

**Comment by cristeigabriel** [comment]
Hello, I can't find anything on this. Could you provide a source?

**Comment by manwiththedrip** [comment]
https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

**Comment by cristeigabriel** [comment]
Probably not worth the trouble now, but I'll keep it in mind. Thanks!
